services:
  app:
    container_name: app
    env_file:
      - .env
      - .env.dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - db
    networks:
      - pl-maker-network

  db:
    container_name: db
    env_file:
      - .env.dev
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    image: mysql:8
    expose:
      - '3306'
    # ports:
    #   - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - pl-maker-network

networks:
  pl-maker-network:
    driver: bridge

volumes:
  mysql-data:
